import os

CORE_DIRECTORY = os.environ["GAME_ENGINE_CORE_DIRECTORY"] if "GAME_ENGINE_CORE_DIRECTORY" in os.environ else "."
OPEN_PIPE_TIMEOUT_SECONDS = 1
WRITE_PIPE_TIMEOUT_SECONDS = 1
READ_PIPE_TIMEOUT_SECONDS = 1
CUMULATIVE_MAX_TIME = 2.5
