import os

CORE_DIRECTORY = os.environ["GAME_ENGINE_CORE_DIRECTORY"] if os.environ["GAME_ENGINE_CORE_DIRECTORY"] is not None else "."
OPEN_PIPE_TIMEOUT_SECONDS = 1
WRITE_PIPE_TIMEOUT_SECONDS = 1
READ_PIPE_TIMEOUT_SECONDS = 1
