from engine.config.pettype import PetType
from engine.game.petabilities import PetAbilities
from engine.game.abilitytype import AbilityType


class PetConfig:
    def __init__(self,
                 pet_name,
                 tier,
                 base_attack,
                 base_health,
                 ability_type,
                 ability_func,):
        self.PET_NAME = pet_name
        self.TIER = tier
        self.BASE_HEALTH = base_health
        self.BASE_ATTACK = base_attack
        self.ABILITY_TYPE = ability_type
        self.ABILITY_FUNC = ability_func

PET_CONFIG = {
    PetType.FISH: PetConfig(pet_name = "Fish",
                        tier = 1,
                        base_attack = 2,
                        base_health = 3,
                        ability_type = AbilityType.LEVEL_UP,
                        ability_func = PetAbilities.fish_ability),

    PetType.BEAVER: PetConfig(pet_name = "Beaver",
                        tier = 1,
                        base_attack = 3,
                        base_health = 2,
                        ability_type= AbilityType.SELL,
                        ability_func= PetAbilities.beaver_ability),

    PetType.PIG: PetConfig(pet_name = "Pig",
                        tier = 1,
                        base_attack = 4,
                        base_health = 1,
                        ability_type = AbilityType.BUY_ROUND_START,
                        ability_func = PetAbilities.pig_ability,),

    PetType.ANT: PetConfig(pet_name = "Ant",
                        tier = 1,
                        base_attack = 2,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.ant_ability),

    PetType.MOSQUITO: PetConfig(pet_name = "Mosquito",
                        tier = 1,
                        base_attack = 2,
                        base_health = 2,
                        ability_type= AbilityType.BATTLE_ROUND_START,
                        ability_func= PetAbilities.mosquito_ability),

    PetType.CRICKET: PetConfig(pet_name = "Cricket",
                        tier = 1,
                        base_attack = 1,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.cricket_ability),
    
    PetType.HORSE: PetConfig(pet_name = "Horse",
                        tier = 1,
                        base_attack = 2,
                        base_health = 1,
                        ability_type= AbilityType.FRIEND_SUMMONED,
                        ability_func= PetAbilities.horse_ability),
    
    PetType.CRAB: PetConfig(pet_name = "Crab",
                        tier = 2,
                        base_attack = 4,
                        base_health = 1,
                        ability_type= AbilityType.BATTLE_ROUND_START,
                        ability_func= PetAbilities.crab_ability),
 
    PetType.SWAN: PetConfig(pet_name = "Swan",
                        tier = 2,
                        base_attack = 1,
                        base_health = 2,
                        ability_type= AbilityType.BUY_ROUND_START,
                        ability_func= PetAbilities.swan_ability),
    
    PetType.HEDGEHOG: PetConfig(pet_name = "Hedgehog",
                        tier = 2,
                        base_attack = 3,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.hedgehog_ability),
    
    PetType.PEACOCK: PetConfig(pet_name = "Peacock",
                        tier = 2,
                        base_attack = 2,
                        base_health = 5,
                        ability_type= AbilityType.HURT,
                        ability_func= PetAbilities.peacock_ability),
    
    PetType.FLAMINGO: PetConfig(pet_name = "Flamingo",
                        tier = 2,
                        base_attack = 3,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.flamingo_ability),
    
    PetType.KANGAROO: PetConfig(pet_name = "Kangaroo",
                        tier = 2,
                        base_attack = 2,
                        base_health = 3,
                        ability_type= AbilityType.FRIEND_AHEAD_ATTACK,
                        ability_func= PetAbilities.kangaroo_ability),

    PetType.SPIDER: PetConfig(pet_name = "Spider",
                        tier = 2,
                        base_attack = 2,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.spider_ability),

    PetType.DODO: PetConfig(pet_name = "Dodo",
                        tier = 3,
                        base_attack = 4,
                        base_health = 2,
                        ability_type= AbilityType.BATTLE_ROUND_START,
                        ability_func= PetAbilities.dodo_ability),
    
    PetType.BADGER: PetConfig(pet_name = "Badger",
                        tier = 3,
                        base_attack = 6,
                        base_health = 3,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.badger_ability),
    
    PetType.DOLPHIN: PetConfig(pet_name = "Dolphin",
                        tier = 3,
                        base_attack = 4,
                        base_health = 3,
                        ability_type= AbilityType.BATTLE_ROUND_START,
                        ability_func= PetAbilities.dolphin_ability),
    
    PetType.GIRAFFE: PetConfig(pet_name = "Giraffe",
                        tier = 3,
                        base_attack = 1,
                        base_health = 3,
                        ability_type= AbilityType.BUY_ROUND_END, 
                        ability_func= PetAbilities.giraffe_ability),
    
    PetType.ELEPHANT: PetConfig(pet_name = "Elephant",
                        tier = 3,
                        base_attack = 3,
                        base_health = 7,
                        ability_type= AbilityType.AFTER_ATTACK,
                        ability_func= PetAbilities.elephant_ability),

    PetType.CAMEL: PetConfig(pet_name = "Camel",
                        tier = 3,
                        base_attack = 2,
                        base_health = 4,
                        ability_type= AbilityType.HURT,
                        ability_func= PetAbilities.camel_ability),
    
    PetType.BUNNY: PetConfig(pet_name = "Bunny",
                        tier = 3,
                        base_attack = 1,
                        base_health = 2,
                        ability_type= AbilityType.FRIEND_ATE_FOOD,
                        ability_func= PetAbilities.bunny_ability),

    PetType.DOG: PetConfig(pet_name = "Dog",
                        tier = 3,
                        base_attack = 2,
                        base_health = 3,
                        ability_type= AbilityType.FRIEND_SUMMONED,
                        ability_func= PetAbilities.dog_ability),

    PetType.SHEEP: PetConfig(pet_name = "Sheep",
                        tier = 3,
                        base_attack = 2,
                        base_health = 2,
                        ability_type= AbilityType.FAINTED,
                        ability_func= PetAbilities.sheep_ability),

    PetType.SKUNK: PetConfig(pet_name = "Skunk",
                        tier = 4,
                        base_attack = 3,
                        base_health = 5,
                        ability_type= AbilityType.BATTLE_ROUND_START,
                        ability_func= PetAbilities.skunk_ability),

    PetType.HIPPO: PetConfig(pet_name = "Hippo",
                        tier = 4,
                        base_attack = 4,
                        base_health = 5,
                        ability_type= AbilityType.KNOCKOUT,
                        ability_func= PetAbilities.hippo_ability),

    PetType.BISON: PetConfig(pet_name = "Bison",
                        tier = 4,
                        base_attack = 4,
                        base_health = 4,
                        ability_type= AbilityType.BUY_ROUND_END,
                        ability_func= PetAbilities.bison_ability),

    PetType.BLOWFISH: PetConfig(pet_name = "Blowfish",
                        tier = 4,
                        base_attack = 3,
                        base_health = 6,
                        ability_type= AbilityType.HURT,
                        ability_func= PetAbilities.blowfish_ability),

    PetType.SQUIRREL: PetConfig(pet_name = "Squirrel",
                        tier = 4,
                        base_attack = 2,
                        base_health = 5,
                        ability_type= AbilityType.BUY_ROUND_START,
                        ability_func= PetAbilities.squirrel_ability),

    PetType.PENGUIN: PetConfig(pet_name = "Penguin",
                        tier = 4,
                        base_attack = 2,
                        base_health = 4,
                        ability_type= AbilityType.BUY_ROUND_END,
                        ability_func= PetAbilities.penguin_ability),

    PetType.BEE: PetConfig(pet_name = "Bee",
                        tier = None,
                        base_attack = 1,
                        base_health = 1,
                        ability_type= None,
                        ability_func= None),

    PetType.RAM: PetConfig(pet_name = "Ram",
                        tier = None,
                        base_attack = None,
                        base_health = None,
                        ability_type= None,
                        ability_func= None),

    PetType.ZOMBIE_CRICKET: PetConfig(pet_name = "Zombie Cricket",
                        tier = None,
                        base_attack = None,
                        base_health = None,
                        ability_type= None,
                        ability_func= None),
}
